### ISSUE TITLE
Can't set metadata on PNG files

### ISSUE THREAD

**Issue by mdedina** [freehep/freehep-vectorgraphics#40]
When using ImageGraphics2D to create a PNG file I don't see any way of setting metadata (such as resolution (DPI)). Perhaps a method can be added for this, similar to AbstractVectorGraphics#setProperties?

**Comment by murkle** [comment]
Here's an example of how to set the DPI in a PNG
https://github.com/geogebra/geogebra/blob/master/desktop/src/main/java/org/geogebra/desktop/io/MyImageIO.java

(doesn't use FreeHEP, not sure why you would need that for PNGs)

**Comment by mdedina** [comment]
Thanks
